# Zsh options
setopt AUTO_CD
setopt C_BASES
setopt CORRECT
setopt MULTIOS
setopt GLOB_DOTS
setopt NO_BG_NICE
setopt ALWAYS_TO_END
setopt NO_LIST_TYPES
setopt TYPESET_SILENT
setopt COMPLETE_IN_WORD
setopt INTERACTIVE_COMMENTS
setopt NO_AUTO_REMOVE_SLASH
