#!/bin/zsh
# Clean systemd journal and coredump
# Clean pacman, AUR and flatpak package caches and orphans

cleanup() {
  (( $+commands[pacman] && $+commands[yay] && $+commands[flatpak] )) || return 1
  yes | yay -Ycc
  { pacman -Qttdq | sudo pacman -Rnsu --noconfirm - } 2> /dev/null; yes | yay -Scc
  flatpak uninstall --unused --assumeyes
  sudo journalctl --rotate && sudo journalctl --vacuum-time=1d
  { sudo rm -rf /var/lib/systemd/coredump/* } > /dev/null 2>&1
}
