#!/bin/zsh
# Redraw prompt

redraw_prompt() {
  (( ${1:-0} )) && {
    echoti civis
    local f
    for f in chpwd "${chpwd_functions[@]}" precmd "${precmd_functions[@]}"; do
      (( ! ${+functions[$f]} )) || "$f" &>/dev/null || true
    done
    zle .reset-prompt
  } always {
    echoti cnorm
  } || zle .reset-prompt && zle -R
}
