#!/bin/zsh
# Function to determine the need of a zcompile. If the .zwc file
# does not exist, or the base file is newer, we need to compile.

zcompile_file() {
  zmodload -F zsh/files b:zf_rm || return
  {
    if [[ -s ${1} && ( ! -s ${1}.zwc || ${1} -nt ${1}.zwc) ]]; then
      zcompile -R -- ${1}.zwc ${1}
    fi
  } always {
    (( $? )) && zf_rm -f -- "$1".zwc 2>/dev/null
  }
}
